### ISSUE TITLE
Adapt bluestar/kernel to use sourcefiles from nuget to compile sccoreerr

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter.ErrorCodes#17]
And remove code for using scerrres.

This is dependent on #5 and #6

**Comment by chrhol** [comment]
There is a feature-branch in git, `feature/errorcodes_as_nuget`, where I have implemented functionality for the project `sccoreerr` to use generated and static files from the package. There are a few minor changes still needed and #6 is not yet fully in place.

**Comment by linkdata** [comment]
I think we can close this one?

**Comment by chrhol** [comment]
Yes, thanks! Closing as done.
