### ISSUE TITLE
ToHelpLink() method

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter.ErrorCodes#19]
What should we do with this functionality. The current implementation uses the value from `StarcounterEnvironment.InternetAddresses.StarcounterWiki` to create an uri to a specific errorcode page.

Since we don't use (will continue to use?) these pages, should this method be removed or the uri changed to something else?

cc @per-samuelsson

**Comment by per-samuelsson** [comment]
It's dependent on what we decide on this:

https://github.com/Starcounter/TechComm/issues/253

Let's try settle on something together, you, me and @Mackiovello, and then adapt to that. I'm open for any suggestion.

**Comment by chrhol** [comment]
@Mackiovello added a searchpage in the docs. The `ToHelpLink()` method should be adapted with the url described in https://github.com/Starcounter/TechComm/issues/253#issuecomment-296568896

**Comment by chrhol** [comment]
Updated.
