### ISSUE TITLE
Typo in exception text: Instantiation of aN object failed ...

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter.ErrorCodes#30]
There is a [typo](https://github.com/Starcounter/Starcounter.ErrorCodes/blob/20ec0302626589c421ef15d1901ae5bfb6761650/src/errorcodes.xml#L1659):

>Instantiation of a object failed because the object wasn't a registered ...

Should be:

>Instantiation of **an** object failed because the object wasn't a registered

**Comment by chrhol** [comment]
Fixed and pushed now.
