### ISSUE TITLE
Cannot build ErrorCodes on Linux

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/Starcounter.ErrorCodes#38]
We want to be able to do this because of the new integration builds.

There are two issues

* Referenced assemblies .NETFramework,Version=v4.5/.NETFramework,Version=v4.6 cannot be found
* Assembly signing is not supported. 

Link to DevelopPlaygroundLinux TC build with log: https://teamcity.starcounter.org/viewLog.html?buildId=52891&buildTypeId=Bifrost_IntegrationNovaLinux&tab=buildLog&_focus=664

This entire issue is exactly the same as https://github.com/Starcounter/Starcounter.BluestarFFI/issues/22

cc @Mackiovello @chrhol @per-samuelsson @miyconst

**Comment by Mackiovello** [comment]
Yes, ErrorCodes targets net45 and net46: https://github.com/Starcounter/Starcounter.ErrorCodes/blob/master/src/Starcounter.ErrorCodes/Starcounter.ErrorCodes.csproj#L6

**Comment by per-samuelsson** [comment]
> Yes, ErrorCodes targets net45 and net46: 

Please, consider this https://github.com/Starcounter/Starcounter.BluestarFFI/issues/22#issuecomment-381053564

**Comment by Mackiovello** [comment]
The fix for the signing issue is here: https://github.com/dotnet/cli/issues/6911#issuecomment-309647478

Tried with BluestarFFI

**Comment by Mackiovello** [comment]
PR created: https://github.com/Starcounter/Starcounter.ErrorCodes/pull/39

**Comment by Mackiovello** [comment]
Fixed with https://github.com/Starcounter/Starcounter.ErrorCodes/pull/39
