### ISSUE TITLE
Make it possible to opt out of help page and version information

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Starcounter.ErrorCodes#50]
See https://github.com/Starcounter/Starcounter.Nova/pull/548,

In Nova we get these kind of error messages:

```
With Experimental:
ScErrSQLIncorrectSyntax (SCERR7021): Incorrect SQL syntax. Unexpected token. The error near or at position Line 1 Col 19, near or at token: p
In query: SELECT p FROSDASD p
Version: 0.0.0.
Help page: https://docs.starcounter.io/?q=SCERR7021.
```

The version seems to always be 0.0.0 and help page doesn't make any sense on Nova, so I'd like to be able to opt out of them.

**Comment by miyconst** [comment]
For release we shall either remove the help link or create a valid help page, even if it's not going to contain much useful information at the beginning.

For RC we might let it slip away, even though it's quite ugly.

cc @bigwad, @per-samuelsson, @dan31

**Comment by bigwad** [comment]
The link will work if we keep hosting on docs.starcounter.io, won't it?

**Comment by miyconst** [comment]
Depends on what we define as "work". As of right now, it just leads to search of `docs.starcounter.io`, which is very unattractive in my point of view. If we provide a link - there shall be a dedicated page or at least a paragraph for every exception.

Also version the number has to be fixed.

**Comment by miyconst** [comment]
The version info has been fixed, the [error codes page](https://github.com/Starcounter/Docs/blob/3.0.0-rc/docs/error-codes.md) has been added to the docs. Closing this issue for Starcounter 3.0 RC.

Any further work shall be done in scope of new issues.
